Repository CoalAI/pos-app, pull requests merged in 2021-07, with the labels that each got.

#81 Feature/company info
  public/favicon.png
  public/index.html
  src/components/admin/Department.vue
  src/components/admin/DepartmentAddEdit.vue
  src/main.ts
  src/store/models/company.ts
  src/store/modules/auth/actions.ts
Labels: bug, enhancement

#84 feat(token): token printing and login bugs
  src/components/auth/Login.vue
  src/components/sales/AddEditUser.vue
  src/components/sales/Order.vue
  src/components/sales/OrderBill.vue
  src/store/modules/auth/actions.ts
Labels: bug, enhancement

#88 feat(changes): changes asked by client
  src/components/admin/Expense.vue
  src/components/admin/ExpenseSummary.vue
  src/components/admin/ZeroOrder.vue
Labels: enhancement

#85 feat(products): pagination added
  src/components/common-components/Paginator.vue
  src/components/sales/Product.vue
  src/store/modules/order/actions.ts
  src/store/modules/order/getters.ts
  src/store/modules/order/mutations.ts
  src/store/modules/order/state.ts
Labels: 3, enhancement

#79 Feature/ProductVariant&RegularCustomer
  src/components/sales/AddEditBatch.vue
  src/components/sales/AddEditProduct.vue
  src/components/sales/Order.vue
  src/store/models/product.ts
  src/store/models/user.ts
  src/store/modules/auth/actions.ts
Labels: enhancement

#92 feature/socketio-plugin
  package-lock.json
  package.json
  src/components/common-components/Header.vue
  src/components/common-components/Notifications.vue
  src/main.ts
  src/plugins/socket-io/index.ts
  src/plugins/socket-io/logger.ts
  src/router.ts
  src/shims-vuex.d.ts
  src/store/models/notification.ts
  src/store/modules/auth/actions.ts
  src/store/modules/auth/getters.ts
  src/store/modules/auth/mutations.ts
  src/store/modules/auth/state.ts
Labels: 3, enhancement

#90 feat(url): login route separated
  src/components/Home.vue
  src/components/auth/Login.vue
  src/components/common-components/Header.vue
  src/permissions.ts
  src/router.ts
Labels: enhancement

#93 Feature/notifiactions panel
  package-lock.json
  src/assets/arrow.png
  src/assets/bell.png
  src/assets/email.png
  src/assets/overflow.png
  src/components/admin/Inventory.vue
  src/components/common-components/Header.vue
  src/components/common-components/Notifications.vue
  src/store/models/notification.ts
  src/store/modules/auth/actions.ts
  src/store/modules/auth/mutations.ts
Labels: enhancement

#103 feat(order): auto select product on barcode entered
  src/components/sales/Order.vue
Labels: 2

#96 feat(search): product-contains-search
  src/components/sales/Batch.vue
  src/router.ts
  src/store/modules/order/actions.ts
Labels: enhancement

#94 Deploy/staging
  README.md
  package-lock.json
  package.json
  public/favicon.png
  public/index.html
  src/assets/arrow.png
  src/assets/bell.png
  src/assets/email.png
  src/assets/overflow.png
  src/components/Home.vue
  src/components/admin/Department.vue
  src/components/admin/DepartmentAddEdit.vue
  src/components/admin/Expense.vue
  src/components/admin/ExpenseSummary.vue
  src/components/admin/Inventory.vue
  src/components/admin/ZeroOrder.vue
  src/components/auth/Login.vue
  src/components/common-components/Header.vue
  src/components/common-components/Modal.vue
  src/components/common-components/Notifications.vue
  src/components/common-components/Paginator.vue
  src/components/sales/AddEditBatch.vue
  src/components/sales/AddEditProduct.vue
  src/components/sales/AddEditUser.vue
  src/components/sales/Batch.vue
  src/components/sales/Order.vue
  src/components/sales/OrderBill.vue
  src/components/sales/Product.vue
  src/main.ts
  src/permissions.ts
  src/plugins/socket-io/index.ts
  src/plugins/socket-io/logger.ts
  src/router.ts
  src/shims-vuex.d.ts
  src/store/models/company.ts
  src/store/models/notification.ts
  src/store/models/product.ts
  src/store/models/user.ts
  src/store/modules/auth/actions.ts
  src/store/modules/auth/getters.ts
  src/store/modules/auth/mutations.ts
  src/store/modules/auth/state.ts
  src/store/modules/order/actions.ts
  src/store/modules/order/getters.ts
  src/store/modules/order/mutations.ts
  src/store/modules/order/state.ts
Labels: help wanted

#104 feat(finance): expense-page-change-to-finance
  src/components/admin/Expense.vue
  src/components/common-components/Header.vue
Labels: enhancement

#108 feat(order): auto focus change on key presses closes #105
  src/components/sales/Order.vue
Labels: 3

#110 Feature/pagination and bakery entry
  src/components/admin/Department.vue
  src/components/admin/Expense.vue
  src/components/admin/ExpenseSummary.vue
  src/components/admin/Inventory.vue
  src/components/admin/Vendor.vue
  src/components/admin/ZeroOrder.vue
  src/components/sales/OrdersList.vue
  src/components/sales/Product.vue
  src/components/sales/Response.vue
  src/components/sales/User.vue
  src/store/modules/auth/actions.ts
  src/store/modules/auth/getters.ts
  src/store/modules/auth/mutations.ts
  src/store/modules/auth/state.ts
  src/store/modules/order/actions.ts
  src/store/modules/order/getters.ts
  src/store/modules/order/mutations.ts
  src/store/modules/order/state.ts
Labels: enhancement
