Repository CoalAI/pos-app, pull requests merged in 2021-08, with the labels that each got.

#112 Deploy to Staging
  src/components/admin/Department.vue
  src/components/admin/Expense.vue
  src/components/admin/ExpenseSummary.vue
  src/components/admin/Inventory.vue
  src/components/admin/Vendor.vue
  src/components/admin/ZeroOrder.vue
  src/components/common-components/Header.vue
  src/components/sales/Order.vue
  src/components/sales/OrdersList.vue
  src/components/sales/Product.vue
  src/components/sales/Response.vue
  src/components/sales/User.vue
  src/store/modules/auth/actions.ts
  src/store/modules/auth/getters.ts
  src/store/modules/auth/mutations.ts
  src/store/modules/auth/state.ts
  src/store/modules/order/actions.ts
  src/store/modules/order/getters.ts
  src/store/modules/order/mutations.ts
  src/store/modules/order/state.ts
Labels: enhancement

#113 Staging
  .github/workflows/deploy_staging.yml
  README.md
  package-lock.json
  package.json
  public/favicon.png
  public/index.html
  src/assets/arrow.png
  src/assets/bell.png
  src/assets/email.png
  src/assets/overflow.png
  src/components/Home.vue
  src/components/admin/Department.vue
  src/components/admin/DepartmentAddEdit.vue
  src/components/admin/Expense.vue
  src/components/admin/ExpenseSummary.vue
  src/components/admin/Inventory.vue
  src/components/admin/Vendor.vue
  src/components/admin/ZeroOrder.vue
  src/components/auth/Login.vue
  src/components/common-components/Header.vue
  src/components/common-components/Modal.vue
  src/components/common-components/Notifications.vue
  src/components/common-components/Paginator.vue
  src/components/sales/AddEditBatch.vue
  src/components/sales/AddEditProduct.vue
  src/components/sales/AddEditUser.vue
  src/components/sales/Batch.vue
  src/components/sales/Order.vue
  src/components/sales/OrderBill.vue
  src/components/sales/OrdersList.vue
  src/components/sales/Product.vue
  src/components/sales/Response.vue
  src/components/sales/User.vue
  src/main.ts
  src/permissions.ts
  src/plugins/socket-io/index.ts
  src/plugins/socket-io/logger.ts
  src/router.ts
  src/shims-vuex.d.ts
  src/store/models/company.ts
  src/store/models/notification.ts
  src/store/models/product.ts
  src/store/models/user.ts
  src/store/modules/auth/actions.ts
  src/store/modules/auth/getters.ts
  src/store/modules/auth/mutations.ts
  src/store/modules/auth/state.ts
  src/store/modules/order/actions.ts
  src/store/modules/order/getters.ts
  src/store/modules/order/mutations.ts
  src/store/modules/order/state.ts
Labels: enhancement

#122 feat(zeroorder): autofocus and product select from keyboard Closes #117
  src/components/admin/ZeroOrder.vue
  src/components/sales/Order.vue
Labels: enhancement, 3

#123 feat(finance): auto-request-and-transaction
  src/components/admin/Expense.vue
  src/components/sales/Response.vue
Labels: enhancement

#127 Feature/inventory access
  src/components/admin/Inventory.vue
  src/components/sales/AddEditProduct.vue
  src/components/sales/Order.vue
  src/store/modules/order/actions.ts
  src/store/modules/order/getters.ts
  src/store/modules/order/mutations.ts
  src/store/modules/order/state.ts
Labels: enhancement

#126 feat(order): key control on barcode field order page and zeroorder pa…
  src/components/admin/ZeroOrder.vue
  src/components/sales/Order.vue
Labels: 2

#128 feat(orderlist): fix order list page issues
  src/components/common-components/Header.vue
  src/components/common-components/Notifications.vue
  src/components/sales/EditOrder.vue
  src/components/sales/OrdersList.vue
  src/main.ts
  src/store/modules/order/actions.ts
  src/store/modules/order/getters.ts
  src/utils/permission_utils.ts
Labels: 3

#130 feat(order): totalPrice-can-be-changes
  src/components/admin/ZeroOrder.vue
  src/components/sales/Order.vue
Labels: enhancement, 2

#134 feat(order&zeroOrder): autoscroll with down/up key
  src/components/admin/ZeroOrder.vue
  src/components/sales/Order.vue
  src/store/modules/order/actions.ts
Labels: 3

#136 Fix/price issue
  .github/workflows/deploy.yml
  .github/workflows/deploy_staging.yml
  README.md
  src/components/admin/ZeroOrder.vue
  src/components/sales/Order.vue
  src/main.ts
  src/store/modules/order/actions.ts
Labels: enhancement

#137 Dev to Staging
  .github/workflows/deploy.yml
  src/components/admin/ZeroOrder.vue
  src/components/sales/Order.vue
  src/main.ts
  src/store/modules/order/actions.ts
Labels: enhancement

#138 Staging to production
  src/components/admin/ZeroOrder.vue
  src/components/sales/Order.vue
  src/store/modules/order/actions.ts
Labels: enhancement

#139 feat(returnorder): return order feature added for sales
  src/components/sales/Order.vue
  src/store/models/order.ts
Labels: 4
