Repository CoalAI/pos-app, pull requests merged in 2021-09, with the labels that each got.

#151 feat(pwa): pwa-and-caching
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/rohi.png
  public/service-worker-dev.js
  src/main.ts
  sw-config.js
Labels: enhancement

#153 fix(order): decimal places fixed
  src/components/sales/Order.vue
Labels: 1

#154 Dev to staging
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/rohi.png
  public/service-worker-dev.js
  src/components/sales/Order.vue
  src/main.ts
  src/store/models/order.ts
  sw-config.js
Labels: Ship features

#156 Staging to Production Ship
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/rohi.png
  public/service-worker-dev.js
  src/components/sales/Order.vue
  src/main.ts
  src/store/models/order.ts
  sw-config.js
Labels: Ship features

#155 Feature/offline mood management
  src/assets/no-signal.png
  src/assets/wifi-router.png
  src/assets/wifi.png
  src/components/common-components/ConnectionError.vue
  src/components/common-components/Header.vue
  src/main.ts
  src/permissions.ts
  src/router.ts
  src/store/index.ts
  src/store/models/root.ts
Labels: enhancement

#160 feat(paginator): page size increased
  src/components/common-components/Paginator.vue
Labels: enhancement

#161 Dev to staging
  src/assets/no-signal.png
  src/assets/wifi-router.png
  src/assets/wifi.png
  src/components/common-components/ConnectionError.vue
  src/components/common-components/Header.vue
  src/components/common-components/Paginator.vue
  src/components/sales/Order.vue
  src/main.ts
  src/permissions.ts
  src/router.ts
  src/store/index.ts
  src/store/models/root.ts
Labels: Ship features

#162 Staging to production
  src/assets/no-signal.png
  src/assets/wifi-router.png
  src/assets/wifi.png
  src/components/common-components/ConnectionError.vue
  src/components/common-components/Header.vue
  src/components/common-components/Paginator.vue
  src/components/sales/Order.vue
  src/main.ts
  src/permissions.ts
  src/router.ts
  src/store/index.ts
  src/store/models/root.ts
Labels: 3

#172 notification enabled
  src/components/common-components/Header.vue
  src/components/common-components/Notifications.vue
  src/main.ts
  src/plugins/socket-io/index.ts
Labels: 2

#171 Fix/demo bugs
  src/components/admin/Department.vue
  src/components/sales/AddEditProduct.vue
  src/components/sales/AddEditUser.vue
  src/components/sales/EditOrder.vue
  src/components/sales/OrdersList.vue
  src/permissions.ts
  src/store/modules/auth/getters.ts
  src/store/modules/order/actions.ts
Labels: bug, 3

#173 Dev to Staging
  src/components/admin/Department.vue
  src/components/common-components/Header.vue
  src/components/common-components/Notifications.vue
  src/components/sales/AddEditProduct.vue
  src/components/sales/AddEditUser.vue
  src/components/sales/EditOrder.vue
  src/components/sales/OrdersList.vue
  src/main.ts
  src/permissions.ts
  src/plugins/socket-io/index.ts
  src/store/modules/auth/getters.ts
  src/store/modules/order/actions.ts
Labels: Ship features

#176 bill template changes
  src/components/sales/OrderBill.vue
Labels: 3

#179 feat(invoice): diable-btn-sumit-order
  src/components/admin/ZeroOrder.vue
  src/components/sales/Order.vue
Labels: bug

#178 Feature/reverse transaction
  src/components/Home.vue
  src/components/admin/Expense.vue
  src/components/admin/ExpenseSummary.vue
  src/components/sales/Response.vue
  src/components/sales/User.vue
  src/store/modules/auth/getters.ts
  src/store/modules/request.ts
Labels: enhancement

#181 order from multiple batches
  src/components/sales/Order.vue
  src/components/sales/OrderBill.vue
Labels: 4

#180 Feature/analytics
  src/components/analytics/Basic.vue
  src/components/analytics/Finance.vue
  src/components/analytics/Inventory.vue
  src/components/analytics/Order.vue
  src/components/common-components/Header.vue
  src/components/sales/OrdersList.vue
  src/router.ts
  src/store/modules/order/actions.ts
  src/store/modules/order/getters.ts
  src/store/modules/order/mutations.ts
  src/store/modules/order/state.ts
Labels: enhancement

#182 dev to staging
  src/components/Home.vue
  src/components/admin/Expense.vue
  src/components/admin/ExpenseSummary.vue
  src/components/admin/ZeroOrder.vue
  src/components/analytics/Basic.vue
  src/components/analytics/Finance.vue
  src/components/analytics/Inventory.vue
  src/components/analytics/Order.vue
  src/components/common-components/Header.vue
  src/components/sales/Order.vue
  src/components/sales/OrderBill.vue
  src/components/sales/OrdersList.vue
  src/components/sales/Response.vue
  src/components/sales/User.vue
  src/router.ts
  src/store/modules/auth/getters.ts
  src/store/modules/order/actions.ts
  src/store/modules/order/getters.ts
  src/store/modules/order/mutations.ts
  src/store/modules/order/state.ts
  src/store/modules/request.ts
Labels: 1

#183 Staging
  src/components/Home.vue
  src/components/admin/Department.vue
  src/components/admin/Expense.vue
  src/components/admin/ExpenseSummary.vue
  src/components/admin/ZeroOrder.vue
  src/components/analytics/Basic.vue
  src/components/analytics/Finance.vue
  src/components/analytics/Inventory.vue
  src/components/analytics/Order.vue
  src/components/common-components/Header.vue
  src/components/common-components/Notifications.vue
  src/components/sales/AddEditProduct.vue
  src/components/sales/AddEditUser.vue
  src/components/sales/EditOrder.vue
  src/components/sales/Order.vue
  src/components/sales/OrderBill.vue
  src/components/sales/OrdersList.vue
  src/components/sales/Response.vue
  src/components/sales/User.vue
  src/main.ts
  src/permissions.ts
  src/plugins/socket-io/index.ts
  src/router.ts
  src/store/modules/auth/getters.ts
  src/store/modules/order/actions.ts
  src/store/modules/order/getters.ts
  src/store/modules/order/mutations.ts
  src/store/modules/order/state.ts
  src/store/modules/request.ts
Labels: enhancement
