Repository CoalAI/pos-app, pull requests merged in 2022-04, with the labels that each got.

#245 Sales order offline bugs
  src/components/sales/Order.vue
Labels: 2

#246 sales order page responsiveness issue
  src/components/sales/Order.vue
Labels: 2

#239 Inventory Page Bugs (front end)
  src/components/admin/Inventory.vue
Labels: 3

#244 front end bugs
  src/components/admin/Vendor.vue
  src/components/admin/VendorAddEdit.vue
  src/components/sales/Batch.vue
  src/components/sales/Product.vue
  src/router.ts
Labels: 3

#243 front end bugs
  src/components/sales/AddEditProduct.vue
  src/components/sales/Product.vue
Labels: 3

#248 Department and Request Page bugs
  src/components/admin/Department.vue
  src/components/admin/DepartmentAddEdit.vue
  src/components/admin/ExpenseSummary.vue
  src/components/admin/Inventory.vue
  src/components/admin/Vendor.vue
  src/components/admin/VendorAddEdit.vue
  src/components/sales/AddEditBatch.vue
  src/components/sales/AddEditProduct.vue
  src/components/sales/AddEditUser.vue
  src/components/sales/Request.vue
  src/components/sales/Response.vue
  src/components/sales/User.vue
Labels: 3

#253 Order Page Bugs
  src/components/admin/ZeroOrder.vue
  src/components/common-components/Header.vue
Labels: 3

#255 Printing Issue
  src/components/sales/OrderBill.vue
Labels: 5

#258 bill changes
  src/components/sales/OrderBill.vue
Labels: 2

#261 Front end issues
  src/components/admin/Department.vue
  src/components/admin/DepartmentAddEdit.vue
  src/components/admin/Expense.vue
  src/components/admin/ExpenseSummary.vue
  src/components/admin/Inventory.vue
  src/components/admin/Vendor.vue
  src/components/admin/VendorAddEdit.vue
  src/components/admin/ZeroOrder.vue
  src/components/analytics/Basic.vue
  src/components/analytics/StockStatement.vue
  src/components/sales/AddEditBatch.vue
  src/components/sales/AddEditProduct.vue
  src/components/sales/AddEditUser.vue
  src/components/sales/Product.vue
  src/components/sales/Request.vue
  src/components/sales/Response.vue
  src/components/sales/User.vue
Labels: 3

#264 Fix product Results
  src/components/sales/Order.vue
Labels: 2
