Repository CoalAI/pos-app, pull requests merged in 2022-03, with the labels that each got.

#209 Integrate backend API of Stock Statement
  src/components/analytics/StockStatement.vue
  src/store/modules/order/actions.ts
Labels: 3

#208 Integrate Operators Sale page with Backend API
  src/components/analytics/Sales_Detail.vue
  src/store/modules/order/actions.ts
  src/store/modules/order/getters.ts
  src/store/modules/order/mutations.ts
  src/store/modules/order/state.ts
Labels: enhancement

#229 R&D on Offline Database
  package-lock.json
  package.json
  src/components/Home.vue
  src/components/admin/ZeroOrder.vue
  src/components/auth/Login.vue
  src/components/common-components/Header.vue
  src/components/common-components/Loader.vue
  src/components/common-components/Paginator.vue
  src/components/sales/Order.vue
  src/main.ts
  src/store/index.ts
  src/store/models/root.ts
  src/store/modules/auth/actions.ts
  src/store/modules/order/actions.ts
  src/utils/offline-store/index.ts
  src/utils/offline-store/table.ts
  src/utils/request.ts
Labels: 3

#234 Front End Changes
  package-lock.json
  src/components/Home.vue
  src/components/admin/ZeroOrder.vue
  src/components/common-components/Header.vue
Labels: 3

#233 Create Frontend Page for Setting
  src/components/common-components/Settings.vue
Labels: 3

#235 Sync orders in offline db
  src/components/admin/ZeroOrder.vue
  src/components/auth/Login.vue
  src/store/models/orderItem.ts
  src/store/modules/order/actions.ts
  src/utils/offline-store/index.ts
Labels: 3

#238 Offline DB for sales user order page
  src/components/sales/Order.vue
Labels: 3

#241 Sales order page bugs (front end)
  package-lock.json
  src/components/sales/Order.vue
Labels: 3

#242 offline order sync issue
  src/utils/offline-store/index.ts
Labels: 2
