Repository CoalAI/pos-app, pull requests merged in 2022-10, with the labels that each got.

#359 Calculation error
  src/components/admin/ZeroOrder.vue
  src/components/sales/Order.vue
  src/components/sales/OrderBill.vue
  src/components/sales/OrdersList.vue
Labels: 5

#358 Add Print in Summary
  src/components/admin/ExpenseSummary.vue
Labels: 2 hrs

#360 Add checkbox in Stock statement
  src/components/analytics/StockStatement.vue
  src/store/modules/order/actions.ts
Labels: 5 hrs
