Repository CoalAI/pos-app, pull requests merged in 2022-09, with the labels that each got.

#354 Finance and Summary Page Updated
  src/components/admin/Expense.vue
  src/components/admin/ExpenseSummary.vue
  src/store/models/transaction.ts
Labels: 4

#350 Offline Database
  src/components/admin/ZeroOrder.vue
  src/components/sales/OfflineOrderBill.vue
  src/components/sales/Order.vue
  src/permissions.ts
  src/store/modules/auth/actions.ts
  src/store/modules/order/actions.ts
  src/utils/offline-store/index.ts
Labels: 3

#349 Upgrade Return Order
  src/components/admin/ZeroOrder.vue
Labels: 3 hrs
